// Code generated by charm-generator; DO NOT EDIT.
package registry

import (
    charms "tfutils-go/charms"
    "github.com/ImGajeed76/charmer/pkg/charmer/models"
)

var RegisteredCharms = map[string]models.CharmFunc{
    "Greeting": {
        Name:    "Greeting",
        Doc:     `Greeting godoc
@Charm
@Title Greeting
@Description
# Greeting
## Description
This is a simple greeting function that asks for a name and greets the user.`,
        Execute: charms.Greeting,
		Path:    "Greeting",
		Title:   "Greeting",
		Description: `# Greeting
## Description
This is a simple greeting function that asks for a name and greets the user.`,
    },
}
